package com.ayshriv.recruitment.job.service;

import com.ayshriv.recruitment.client.entity.Client;
import com.ayshriv.recruitment.client.repository.ClientRepository;
import com.ayshriv.recruitment.common.exception.BadRequestException;
import com.ayshriv.recruitment.common.security.SecurityContextService;
import com.ayshriv.recruitment.job.dto.request.ChangeJobClientRequest;
import com.ayshriv.recruitment.job.dto.request.CreateJobRequest;
import com.ayshriv.recruitment.job.dto.request.UpdateJobRequest;
import com.ayshriv.recruitment.job.dto.request.UpdateJobStatusRequest;
import com.ayshriv.recruitment.job.dto.response.JobResponse;
import com.ayshriv.recruitment.job.dto.response.JobSummaryResponse;
import com.ayshriv.recruitment.job.entity.EmploymentType;
import com.ayshriv.recruitment.job.entity.ExperienceLevel;
import com.ayshriv.recruitment.job.entity.Job;
import com.ayshriv.recruitment.job.entity.JobPriority;
import com.ayshriv.recruitment.job.entity.JobStatus;
import com.ayshriv.recruitment.job.exception.JobAccessDeniedException;
import com.ayshriv.recruitment.job.exception.JobNotFoundException;
import com.ayshriv.recruitment.job.mapper.JobMapper;
import com.ayshriv.recruitment.job.repository.JobRepository;
import com.ayshriv.recruitment.job.specification.JobSpecification;
import com.ayshriv.recruitment.organization.entity.Organization;
import com.ayshriv.recruitment.organization.exception.OrganizationNotFoundException;
import com.ayshriv.recruitment.organization.repository.OrganizationRepository;
import com.ayshriv.recruitment.user.entity.User;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;

/**
 * Business logic for job / opening management.
 *
 * <p>Every operation is tenant-bound: the organization id is always resolved
 * from the security context (never from the client) and every lookup verifies
 * that the target job belongs to the authenticated organization. A job of
 * another organization surfaces as {@code 403 FORBIDDEN}, a missing or
 * soft-deleted job as {@code 404 NOT FOUND}.</p>
 *
 * <p>Job codes are generated by the backend. Allocation is serialized per
 * tenant with a pessimistic lock on the organization row and backed by the
 * {@code (ORGANIZATION_ID, JOB_CODE)} unique constraint, so concurrent
 * creations can never receive the same code.</p>
 *
 * <p>Jobs always belong to the same tenant as their owning client; the client
 * is verified to belong to the authenticated organization before a job is
 * created or reassigned. Lifecycle changes are validated through
 * {@link JobStatusTransitionService}, deletion is always a soft delete.</p>
 */
@Service
@RequiredArgsConstructor
public class JobService {

    /**
     * Machine readable code returned when the experience range is invalid.
     */
    public static final String INVALID_EXPERIENCE_RANGE = "INVALID_EXPERIENCE_RANGE";

    /**
     * Machine readable code returned when the salary range is invalid.
     */
    public static final String INVALID_SALARY_RANGE = "INVALID_SALARY_RANGE";

    private final JobRepository jobRepository;
    private final ClientRepository clientRepository;
    private final OrganizationRepository organizationRepository;
    private final JobMapper jobMapper;
    private final JobCodeGenerator jobCodeGenerator;
    private final JobStatusTransitionService jobStatusTransitionService;
    private final SecurityContextService securityContextService;

    /**
     * Create a job within the authenticated organization.
     *
     * @param organizationId authenticated tenant id
     * @param request        creation payload
     * @return created job
     */
    @Transactional
    public JobResponse createJob(Long organizationId, CreateJobRequest request) {
        validateExperienceRange(request.getMinExperience(), request.getMaxExperience());
        validateSalaryRange(request.getSalaryMin(), request.getSalaryMax());
        Client client = verifyClientInOrganization(organizationId, request.getClientId());
        lockOrganization(organizationId);

        Job job = jobMapper.toEntity(request);
        job.setOrganization(new Organization(organizationId));
        job.setClient(client);
        job.setJobCode(jobCodeGenerator.nextCode(organizationId));
        job.setStatus(JobStatus.DRAFT);
        job.setActive(true);
        securityContextService.getCurrentUserId().ifPresent(userId -> job.setCreatedBy(new User(userId)));

        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Get a single job by id.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return requested job
     * @throws JobNotFoundException    when the job is missing or soft deleted
     * @throws JobAccessDeniedException when the job belongs to another organization
     */
    @Transactional(readOnly = true)
    public JobResponse getJobById(Long organizationId, Long jobId) {
        return jobMapper.toResponse(findJobInOrganization(organizationId, jobId));
    }

    /**
     * Page through all non deleted jobs of the authenticated organization.
     *
     * @param organizationId authenticated tenant id
     * @param status         optional status filter
     * @param priority       optional priority filter
     * @param clientId       optional owning client filter
     * @param employmentType optional employment type filter
     * @param experienceLevel optional experience level filter
     * @param pageable       pagination and sorting
     * @return page of jobs
     */
    @Transactional(readOnly = true)
    public Page<JobResponse> getJobs(Long organizationId, JobStatus status, JobPriority priority,
                                     Long clientId, EmploymentType employmentType,
                                     ExperienceLevel experienceLevel, Pageable pageable) {
        Specification<Job> spec = Specification
                .where(JobSpecification.belongsToOrganization(organizationId))
                .and(JobSpecification.notDeleted());
        if (status != null) {
            spec = spec.and(JobSpecification.status(status));
        }
        if (priority != null) {
            spec = spec.and(JobSpecification.priority(priority));
        }
        if (clientId != null) {
            spec = spec.and(JobSpecification.belongsToClient(clientId));
        }
        if (employmentType != null) {
            spec = spec.and(JobSpecification.employmentType(employmentType));
        }
        if (experienceLevel != null) {
            spec = spec.and(JobSpecification.experienceLevel(experienceLevel));
        }
        return jobRepository.findAll(spec, pageable).map(jobMapper::toResponse);
    }

    /**
     * Search non deleted jobs of the authenticated organization.
     *
     * @param organizationId authenticated tenant id
     * @param keyword        optional search keyword
     * @param clientId       optional owning client filter
     * @param status         optional status filter
     * @param priority       optional priority filter
     * @param pageable       pagination and sorting
     * @return page of matching jobs
     */
    @Transactional(readOnly = true)
    public Page<JobSummaryResponse> searchJobs(Long organizationId, String keyword, Long clientId,
                                               JobStatus status, JobPriority priority, Pageable pageable) {
        Specification<Job> spec = Specification
                .where(JobSpecification.belongsToOrganization(organizationId))
                .and(JobSpecification.notDeleted());
        if (keyword != null && !keyword.isBlank()) {
            spec = spec.and(JobSpecification.keyword(keyword.trim()));
        }
        if (clientId != null) {
            spec = spec.and(JobSpecification.belongsToClient(clientId));
        }
        if (status != null) {
            spec = spec.and(JobSpecification.status(status));
        }
        if (priority != null) {
            spec = spec.and(JobSpecification.priority(priority));
        }
        return jobRepository.findAll(spec, pageable).map(jobMapper::toSummaryResponse);
    }

    /**
     * Page through all non deleted jobs of a client within the authenticated
     * organization.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       owning client
     * @param pageable       pagination and sorting
     * @return page of jobs of the client
     * @throws JobAccessDeniedException when the client belongs to another organization
     */
    @Transactional(readOnly = true)
    public Page<JobResponse> getJobsByClient(Long organizationId, Long clientId, Pageable pageable) {
        verifyClientInOrganization(organizationId, clientId);
        return jobRepository.findJobsByClient(clientId, organizationId, pageable)
                .map(jobMapper::toResponse);
    }

    /**
     * Update the profile of a job.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @param request        update payload
     * @return updated job
     */
    @Transactional
    public JobResponse updateJob(Long organizationId, Long jobId, UpdateJobRequest request) {
        validateExperienceRange(request.getMinExperience(), request.getMaxExperience());
        validateSalaryRange(request.getSalaryMin(), request.getSalaryMax());
        Job job = findJobInOrganization(organizationId, jobId);
        jobMapper.updateEntity(job, request);
        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Reassign a job to another client. The new client must belong to the same
     * organization as the job.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @param request        change client payload
     * @return updated job
     */
    @Transactional
    public JobResponse changeJobClient(Long organizationId, Long jobId, ChangeJobClientRequest request) {
        Job job = findJobInOrganization(organizationId, jobId);
        Client newClient = verifyClientInOrganization(organizationId, request.getClientId());
        job.setClient(newClient);
        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Change the status of a job through the generic status endpoint.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @param request        target status payload
     * @return updated job
     * @throws BadRequestException when the transition is not allowed
     */
    @Transactional
    public JobResponse updateJobStatus(Long organizationId, Long jobId, UpdateJobStatusRequest request) {
        Job job = findJobInOrganization(organizationId, jobId);
        jobStatusTransitionService.apply(job, request.getStatus());
        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Publish a draft job.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return published job
     */
    @Transactional
    public JobResponse publishJob(Long organizationId, Long jobId) {
        return changeStatus(organizationId, jobId, JobStatus.OPEN);
    }

    /**
     * Put an open job on hold.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return job on hold
     */
    @Transactional
    public JobResponse putJobOnHold(Long organizationId, Long jobId) {
        return changeStatus(organizationId, jobId, JobStatus.ON_HOLD);
    }

    /**
     * Close an open or on hold job.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return closed job
     */
    @Transactional
    public JobResponse closeJob(Long organizationId, Long jobId) {
        return changeStatus(organizationId, jobId, JobStatus.CLOSED);
    }

    /**
     * Cancel a draft, open or on hold job.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return cancelled job
     */
    @Transactional
    public JobResponse cancelJob(Long organizationId, Long jobId) {
        return changeStatus(organizationId, jobId, JobStatus.CANCELLED);
    }

    /**
     * Activate a job. Jobs that are closed or cancelled cannot be reactivated.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return activated job
     */
    @Transactional
    public JobResponse activateJob(Long organizationId, Long jobId) {
        Job job = findJobInOrganization(organizationId, jobId);
        if (job.getStatus() == JobStatus.CLOSED || job.getStatus() == JobStatus.CANCELLED) {
            throw new BadRequestException(
                    "A closed or cancelled job cannot be activated",
                    "JOB_CANNOT_BE_ACTIVATED");
        }
        job.setActive(true);
        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Deactivate a job without deleting it.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return deactivated job
     */
    @Transactional
    public JobResponse deactivateJob(Long organizationId, Long jobId) {
        Job job = findJobInOrganization(organizationId, jobId);
        job.setActive(false);
        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Soft delete a job. The record is never physically removed.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     */
    @Transactional
    public void deleteJob(Long organizationId, Long jobId) {
        Job job = findJobInOrganization(organizationId, jobId);
        job.softDelete();
        jobRepository.save(job);
    }

    /**
     * Apply a validated status change to a job.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @param target         desired status
     * @return updated job
     */
    private JobResponse changeStatus(Long organizationId, Long jobId, JobStatus target) {
        Job job = findJobInOrganization(organizationId, jobId);
        jobStatusTransitionService.apply(job, target);
        return jobMapper.toResponse(jobRepository.save(job));
    }

    /**
     * Load a non deleted job and verify it belongs to the authenticated
     * organization. A job of another organization is forbidden, a missing or
     * soft-deleted job is not found.
     *
     * @param organizationId authenticated tenant id
     * @param jobId          requested job id
     * @return matching job
     */
    private Job findJobInOrganization(Long organizationId, Long jobId) {
        Job job = jobRepository.findByIdAndNotDeleted(jobId)
                .orElseThrow(() -> new JobNotFoundException(jobId));
        if (!job.getOrganizationId().equals(organizationId)) {
            throw new JobAccessDeniedException();
        }
        return job;
    }

    /**
     * Load a non deleted client entity and verify it belongs to the
     * authenticated organization.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @return matching client
     */
    private Client verifyClientInOrganization(Long organizationId, Long clientId) {
        return clientRepository.findByIdAndOrganization(clientId, organizationId)
                .orElseThrow(() -> new JobNotFoundException(clientId));
    }

    /**
     * Serialize job code allocation for the tenant by taking a pessimistic
     * write lock on the organization row. Concurrent creations for the same
     * organization queue on this lock, so the next code is always derived from
     * committed state.
     *
     * @param organizationId owning tenant
     */
    private void lockOrganization(Long organizationId) {
        organizationRepository.findByIdForUpdate(organizationId)
                .orElseThrow(() -> new OrganizationNotFoundException(organizationId));
    }

    /**
     * Reject experience ranges where the minimum exceeds the maximum.
     *
     * @param minExperience minimum years of experience, may be {@code null}
     * @param maxExperience maximum years of experience, may be {@code null}
     */
    private void validateExperienceRange(Integer minExperience, Integer maxExperience) {
        if (minExperience != null && maxExperience != null && minExperience > maxExperience) {
            throw new BadRequestException(
                    "Min experience cannot be greater than max experience",
                    INVALID_EXPERIENCE_RANGE);
        }
    }

    /**
     * Reject salary ranges where the minimum exceeds the maximum.
     *
     * @param salaryMin minimum salary, may be {@code null}
     * @param salaryMax maximum salary, may be {@code null}
     */
    private void validateSalaryRange(BigDecimal salaryMin, BigDecimal salaryMax) {
        if (salaryMin != null && salaryMax != null && salaryMin.compareTo(salaryMax) > 0) {
            throw new BadRequestException(
                    "Salary min cannot be greater than salary max",
                    INVALID_SALARY_RANGE);
        }
    }
}