package com.ayshriv.recruitment.client.entity;

import com.ayshriv.recruitment.clientContact.entity.ClientContact;
import com.ayshriv.recruitment.common.entity.BaseEntity;
import com.ayshriv.recruitment.organization.entity.Organization;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a client / hiring company that a recruitment agency works with.
 *
 * <p>A client always belongs to exactly one {@link Organization} (the
 * recruitment agency) and can never be moved to another one; the tenant is
 * the hard isolation boundary. Client codes such as {@code CLI-000001} are
 * generated by the backend and unique within the owning organization.</p>
 *
 * <p>The recruitment hierarchy is {@code Organization → Client → Job →
 * Application → Candidate}. Contacts are held on a dedicated table and are
 * exposed only through dedicated contact endpoints, never through this
 * entity.</p>
 *
 * <p>The common persistence fields are inherited from {@link BaseEntity}.</p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "CLIENTS",
        uniqueConstraints = @UniqueConstraint(
                name = "UK_CLIENTS_ORGANIZATION_CLIENT_CODE",
                columnNames = {"ORGANIZATION_ID", "CLIENT_CODE"}))
public class Client extends BaseEntity {

    /**
     * Human readable client code generated by the backend, for example
     * {@code CLI-000001}. Never accepted from a client request and never
     * reused after a soft delete.
     */
    @Basic(optional = false)
    @Column(name = "CLIENT_CODE", nullable = false, length = 20)
    private String clientCode;

    /**
     * Display name of the client company.
     */
    @Basic(optional = false)
    @Column(name = "COMPANY_NAME", nullable = false, length = 200)
    private String companyName;

    /**
     * Registered / legal name of the client company.
     */
    @Column(name = "LEGAL_NAME", length = 255)
    private String legalName;

    /**
     * Primary contact email. Uniqueness is enforced at the application layer
     * within an organization; the same email may exist in other organizations.
     */
    @Basic(optional = false)
    @Column(name = "EMAIL", nullable = false, length = 255)
    private String email;

    /**
     * Primary contact phone number.
     */
    @Column(name = "PHONE", length = 30)
    private String phone;

    /**
     * Client company website URL.
     */
    @Column(name = "WEBSITE", length = 255)
    private String website;

    /**
     * Industry sector, for example {@code Technology}.
     */
    @Column(name = "INDUSTRY", length = 100)
    private String industry;

    /**
     * Company size band, stored as its string value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "COMPANY_SIZE", length = 20)
    private CompanySize companySize;

    /**
     * Country where the client is located.
     */
    @Column(name = "COUNTRY", length = 100)
    private String country;

    /**
     * State / province where the client is located.
     */
    @Column(name = "STATE", length = 100)
    private String state;

    /**
     * City where the client is located.
     */
    @Column(name = "CITY", length = 100)
    private String city;

    /**
     * Street / building address.
     */
    @Column(name = "ADDRESS", length = 500)
    private String address;

    /**
     * Postal / zip code.
     */
    @Column(name = "POSTAL_CODE", length = 20)
    private String postalCode;

    /**
     * IANA timezone of the client, for example {@code Asia/Kolkata}.
     */
    @Column(name = "TIMEZONE", length = 50)
    private String timezone;

    /**
     * Short description of the client company.
     */
    @Column(name = "DESCRIPTION", length = 2000)
    private String description;

    /**
     * Internal recruitment notes about the client.
     */
    @Column(name = "NOTES", length = 2000)
    private String notes;

    /**
     * Owning tenant (the recruitment agency). Never changed after creation.
     */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "ORGANIZATION_ID", nullable = false)
    private Organization organization;

    /**
     * Contacts inside the client company.
     *
     * <p>Lazy loaded and never serialized; exposed exclusively through the
     * dedicated contact endpoints. {@link ClientContact} owns the foreign
     * key.</p>
     */
    @JsonIgnore
    @OneToMany(mappedBy = "client", fetch = FetchType.LAZY)
    private List<ClientContact> contacts = new ArrayList<>();

    /**
     * Owning tenant identifier, safe to access without initializing the lazy
     * relationship target.
     *
     * @return organization id or {@code null} when not set
     */
    public Long getOrganizationId() {
        return organization != null ? organization.getId() : null;
    }

    /**
     * Reference-only constructor used when setting associations by id.
     *
     * @param id client primary key
     */
    public Client(Long id) {
        super(id);
    }
}