package com.ayshriv.recruitment.client.controller;

import com.ayshriv.recruitment.client.dto.request.CreateClientRequest;
import com.ayshriv.recruitment.client.dto.request.UpdateClientRequest;
import com.ayshriv.recruitment.client.dto.response.ClientResponse;
import com.ayshriv.recruitment.client.dto.response.ClientSummaryResponse;
import com.ayshriv.recruitment.client.service.ClientService;
import com.ayshriv.recruitment.common.response.ApiResponse;
import com.ayshriv.recruitment.common.response.ResponseUtil;
import com.ayshriv.recruitment.common.security.SecurityContextService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * REST endpoints for client / hiring company management.
 *
 * <p>Every operation is scoped to the authenticated tenant. The organization
 * is resolved from the API key security context and never accepted from the
 * client; the service rejects any request that targets another organization's
 * client with {@code 403}.</p>
 */
@RestController
@RequestMapping("/api/v1/clients")
@RequiredArgsConstructor
@SecurityRequirement(name = "X-API-KEY")
@Tag(name = "Clients", description = "Client / hiring company management")
public class ClientController {

    private final ClientService clientService;
    private final SecurityContextService securityContextService;

    /**
     * Create a client within the authenticated organization.
     *
     * @param request     creation payload
     * @param httpRequest servlet request for the response path
     * @return created client
     */
    @Operation(
            summary = "Create client",
            description = "Creates a client / hiring company in the authenticated organization. "
                    + "The organization is derived from the API key and the client code is "
                    + "generated by the backend; neither may be supplied in the payload."
    )
    @PostMapping
    public ResponseEntity<ApiResponse<ClientResponse>> create(
            @Valid @RequestBody CreateClientRequest request, HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(ResponseUtil.success(
                        "Client created successfully",
                        clientService.createClient(currentOrganizationId, request),
                        httpRequest.getRequestURI()));
    }

    /**
     * Page through all non deleted clients of the authenticated organization.
     *
     * @param pageable    pagination and sorting
     * @param httpRequest servlet request for the response path
     * @return paginated list of clients
     */
    @Operation(
            summary = "List clients",
            description = "Returns a paginated list of non deleted clients of the "
                    + "authenticated organization."
    )
    @GetMapping
    public ResponseEntity<ApiResponse<List<ClientResponse>>> list(
            @ParameterObject @PageableDefault(size = 20, sort = "createdOn", direction = Sort.Direction.DESC)
            Pageable pageable, HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        Page<ClientResponse> page = clientService.getClients(currentOrganizationId, pageable);
        return ResponseEntity.ok(ResponseUtil.successPage(
                "Clients retrieved successfully", page, httpRequest.getRequestURI()));
    }

    /**
     * Search clients by keyword.
     *
     * @param keyword     search keyword across company name, legal name, email, client code and industry
     * @param pageable    pagination and sorting
     * @param httpRequest servlet request for the response path
     * @return paginated list of matching clients
     */
    @Operation(
            summary = "Search clients",
            description = "Search non deleted clients of the authenticated organization by keyword "
                    + "across company name, legal name, email, client code and industry."
    )
    @GetMapping("/search")
    public ResponseEntity<ApiResponse<List<ClientSummaryResponse>>> search(
            @RequestParam(required = false)
            @Parameter(description = "Keyword matched against company name, legal name, email, client code and industry")
            String keyword,
            @ParameterObject
            @PageableDefault(size = 20, sort = "createdOn", direction = Sort.Direction.DESC)
            Pageable pageable,
            HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        Page<ClientSummaryResponse> page = clientService.searchClients(currentOrganizationId, keyword, pageable);
        return ResponseEntity.ok(ResponseUtil.successPage(
                "Clients retrieved successfully", page, httpRequest.getRequestURI()));
    }

    /**
     * Get a single client by id.
     *
     * @param id          client primary key
     * @param httpRequest servlet request for the response path
     * @return requested client
     */
    @Operation(
            summary = "Get client",
            description = "Returns a single non deleted client. Clients of another "
                    + "organization are rejected with 403."
    )
    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse<ClientResponse>> get(@PathVariable Long id, HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        return ResponseEntity.ok(ResponseUtil.success(
                "Client retrieved successfully",
                clientService.getClientById(currentOrganizationId, id),
                httpRequest.getRequestURI()));
    }

    /**
     * Update a client profile.
     *
     * @param id          client primary key
     * @param request     update payload
     * @param httpRequest servlet request for the response path
     * @return updated client
     */
    @Operation(
            summary = "Update client",
            description = "Updates profile fields of a client. The client code, the tenant, "
                    + "lifecycle timestamps and the activation state cannot be modified through "
                    + "this endpoint; activation is changed through the dedicated endpoints."
    )
    @PutMapping("/{id}")
    public ResponseEntity<ApiResponse<ClientResponse>> update(
            @PathVariable Long id,
            @Valid @RequestBody UpdateClientRequest request,
            HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        return ResponseEntity.ok(ResponseUtil.success(
                "Client updated successfully",
                clientService.updateClient(currentOrganizationId, id, request),
                httpRequest.getRequestURI()));
    }

    /**
     * Activate a client.
     *
     * @param id          client primary key
     * @param httpRequest servlet request for the response path
     * @return activated client
     */
    @Operation(
            summary = "Activate client",
            description = "Sets the active flag of a client to true without changing the "
                    + "deleted flag."
    )
    @PatchMapping("/{id}/activate")
    public ResponseEntity<ApiResponse<ClientResponse>> activate(
            @PathVariable Long id, HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        return ResponseEntity.ok(ResponseUtil.success(
                "Client activated successfully",
                clientService.activateClient(currentOrganizationId, id),
                httpRequest.getRequestURI()));
    }

    /**
     * Deactivate a client.
     *
     * @param id          client primary key
     * @param httpRequest servlet request for the response path
     * @return deactivated client
     */
    @Operation(
            summary = "Deactivate client",
            description = "Sets the active flag of a client to false without deleting the client."
    )
    @PatchMapping("/{id}/deactivate")
    public ResponseEntity<ApiResponse<ClientResponse>> deactivate(
            @PathVariable Long id, HttpServletRequest httpRequest) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        return ResponseEntity.ok(ResponseUtil.success(
                "Client deactivated successfully",
                clientService.deactivateClient(currentOrganizationId, id),
                httpRequest.getRequestURI()));
    }

    /**
     * Soft delete a client.
     *
     * @param id client primary key
     * @return empty response
     */
    @Operation(
            summary = "Delete client",
            description = "Soft deletes a client: the active flag is set to false and the "
                    + "deleted flag to true. The record is not physically removed."
    )
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        Long currentOrganizationId = securityContextService.getCurrentOrganizationId();
        clientService.deleteClient(currentOrganizationId, id);
        return ResponseEntity.noContent().build();
    }
}