package com.ayshriv.recruitment.client.service;

import com.ayshriv.recruitment.client.dto.request.CreateClientRequest;
import com.ayshriv.recruitment.client.dto.request.UpdateClientRequest;
import com.ayshriv.recruitment.client.dto.response.ClientResponse;
import com.ayshriv.recruitment.client.dto.response.ClientSummaryResponse;
import com.ayshriv.recruitment.client.entity.Client;
import com.ayshriv.recruitment.client.exception.ClientAccessDeniedException;
import com.ayshriv.recruitment.client.exception.ClientNotFoundException;
import com.ayshriv.recruitment.client.exception.DuplicateClientException;
import com.ayshriv.recruitment.client.mapper.ClientMapper;
import com.ayshriv.recruitment.client.repository.ClientRepository;
import com.ayshriv.recruitment.common.exception.BadRequestException;
import com.ayshriv.recruitment.organization.entity.Organization;
import com.ayshriv.recruitment.organization.exception.OrganizationNotFoundException;
import com.ayshriv.recruitment.organization.repository.OrganizationRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.ZoneId;

/**
 * Business logic for client / hiring company management.
 *
 * <p>Every operation is tenant-bound: the organization id is always resolved
 * from the security context (never from the client) and every lookup verifies
 * that the target client belongs to the authenticated organization. A client
 * of another organization surfaces as {@code 403 FORBIDDEN}, a missing or
 * soft-deleted client as {@code 404 NOT FOUND}.</p>
 *
 * <p>Client codes are generated by the backend. Allocation is serialized per
 * tenant with a pessimistic lock on the organization row and backed by the
 * {@code (ORGANIZATION_ID, CLIENT_CODE)} unique constraint, so concurrent
 * creations can never receive the same code.</p>
 *
 * <p>Deletion is always a soft delete: the record is never physically
 * removed.</p>
 */
@Service
@RequiredArgsConstructor
public class ClientService {

    /**
     * Machine readable code returned when an invalid timezone is provided.
     */
    public static final String INVALID_TIMEZONE = "INVALID_TIMEZONE";

    private final ClientRepository clientRepository;
    private final OrganizationRepository organizationRepository;
    private final ClientMapper clientMapper;
    private final ClientCodeGenerator clientCodeGenerator;

    /**
     * Create a client within the authenticated organization.
     *
     * @param organizationId authenticated tenant id
     * @param request        creation payload
     * @return created client
     * @throws DuplicateClientException when the email is already used in the organization
     */
    @Transactional
    public ClientResponse createClient(Long organizationId, CreateClientRequest request) {
        validateTimezone(request.getTimezone());
        ensureEmailAvailable(organizationId, request.getEmail(), null);
        lockOrganization(organizationId);

        Client client = clientMapper.toEntity(request);
        client.setOrganization(new Organization(organizationId));
        client.setClientCode(clientCodeGenerator.nextCode(organizationId));

        return clientMapper.toResponse(clientRepository.save(client));
    }

    /**
     * Get a single client by id.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @return requested client
     * @throws ClientNotFoundException  when the client is missing or soft deleted
     * @throws ClientAccessDeniedException when the client belongs to another organization
     */
    @Transactional(readOnly = true)
    public ClientResponse getClientById(Long organizationId, Long clientId) {
        return clientMapper.toResponse(findClientInOrganization(organizationId, clientId));
    }

    /**
     * Page through all non deleted clients of the authenticated organization.
     *
     * @param organizationId authenticated tenant id
     * @param pageable       pagination and sorting
     * @return page of clients
     */
    @Transactional(readOnly = true)
    public Page<ClientResponse> getClients(Long organizationId, Pageable pageable) {
        return clientRepository.findAllByOrganization(organizationId, pageable)
                .map(clientMapper::toResponse);
    }

    /**
     * Search non deleted clients of the authenticated organization by keyword.
     *
     * @param organizationId authenticated tenant id
     * @param keyword        search keyword; blank returns all clients
     * @param pageable       pagination and sorting
     * @return page of matching clients
     */
    @Transactional(readOnly = true)
    public Page<ClientSummaryResponse> searchClients(Long organizationId, String keyword, Pageable pageable) {
        if (keyword == null || keyword.isBlank()) {
            return clientRepository.findAllByOrganization(organizationId, pageable)
                    .map(clientMapper::toSummaryResponse);
        }
        return clientRepository.searchClients(organizationId, keyword.trim(), pageable)
                .map(clientMapper::toSummaryResponse);
    }

    /**
     * Update the profile of a client.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @param request        update payload
     * @return updated client
     */
    @Transactional
    public ClientResponse updateClient(Long organizationId, Long clientId, UpdateClientRequest request) {
        validateTimezone(request.getTimezone());
        Client client = findClientInOrganization(organizationId, clientId);
        if (!request.getEmail().equalsIgnoreCase(client.getEmail())) {
            ensureEmailAvailable(organizationId, request.getEmail(), clientId);
        }
        clientMapper.updateEntity(client, request);
        return clientMapper.toResponse(clientRepository.save(client));
    }

    /**
     * Activate a client without touching the deleted flag.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @return activated client
     */
    @Transactional
    public ClientResponse activateClient(Long organizationId, Long clientId) {
        Client client = findClientInOrganization(organizationId, clientId);
        client.setActive(true);
        return clientMapper.toResponse(clientRepository.save(client));
    }

    /**
     * Deactivate a client without deleting it.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @return deactivated client
     */
    @Transactional
    public ClientResponse deactivateClient(Long organizationId, Long clientId) {
        Client client = findClientInOrganization(organizationId, clientId);
        client.setActive(false);
        return clientMapper.toResponse(clientRepository.save(client));
    }

    /**
     * Soft delete a client. The record is never physically removed.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     */
    @Transactional
    public void deleteClient(Long organizationId, Long clientId) {
        Client client = findClientInOrganization(organizationId, clientId);
        client.softDelete();
        clientRepository.save(client);
    }

    /**
     * Load a non deleted client entity verified to belong to the authenticated
     * organization.
     *
     * <p>Intended for internal use by dependent features (for example the
     * client contact feature) that need the entity to build associations.
     * Exposing the entity is an explicit exception to the DTO rule and is
     * never leaked through API responses.</p>
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @return matching client entity
     */
    @Transactional(readOnly = true)
    public Client getClientEntity(Long organizationId, Long clientId) {
        return findClientInOrganization(organizationId, clientId);
    }

    /**
     * Load a non deleted client and verify it belongs to the authenticated
     * organization. A client of another organization is forbidden, a missing
     * or soft-deleted client is not found.
     *
     * @param organizationId authenticated tenant id
     * @param clientId       requested client id
     * @return matching client
     */
    private Client findClientInOrganization(Long organizationId, Long clientId) {
        Client client = clientRepository.findByIdAndNotDeleted(clientId)
                .orElseThrow(() -> new ClientNotFoundException(clientId));
        if (!client.getOrganizationId().equals(organizationId)) {
            throw new ClientAccessDeniedException();
        }
        return client;
    }

    /**
     * Serialize client code allocation for the tenant by taking a pessimistic
     * write lock on the organization row. Concurrent creations for the same
     * organization queue on this lock, so the next code is always derived from
     * committed state.
     *
     * @param organizationId owning tenant
     */
    private void lockOrganization(Long organizationId) {
        organizationRepository.findByIdForUpdate(organizationId)
                .orElseThrow(() -> new OrganizationNotFoundException(organizationId));
    }

    /**
     * Ensure the email is not already used by another non deleted client of
     * the same organization. Soft deleted clients do not block reuse.
     *
     * @param organizationId owning tenant
     * @param email          candidate email
     * @param excludingId    client id to exclude (own id on update), or {@code null}
     */
    private void ensureEmailAvailable(Long organizationId, String email, Long excludingId) {
        clientRepository.findByEmailAndOrganization(email, organizationId).ifPresent(existing -> {
            if (excludingId == null || !existing.getId().equals(excludingId)) {
                throw DuplicateClientException.forEmail(email);
            }
        });
    }

    /**
     * Reject timezones that are not valid IANA identifiers.
     *
     * @param timezone candidate timezone, may be {@code null} or blank
     */
    private void validateTimezone(String timezone) {
        if (timezone == null || timezone.isBlank()) {
            return;
        }
        if (!ZoneId.getAvailableZoneIds().contains(timezone)) {
            throw new BadRequestException("Invalid timezone: " + timezone, INVALID_TIMEZONE);
        }
    }
}