package com.ayshriv.recruitment.client.mapper;

import com.ayshriv.recruitment.client.dto.request.CreateClientRequest;
import com.ayshriv.recruitment.client.dto.request.UpdateClientRequest;
import com.ayshriv.recruitment.client.dto.response.ClientResponse;
import com.ayshriv.recruitment.client.dto.response.ClientSummaryResponse;
import com.ayshriv.recruitment.client.entity.Client;
import com.ayshriv.recruitment.client.entity.CompanySize;
import org.springframework.stereotype.Component;

/**
 * Converts between client request / response DTOs and the JPA entity.
 *
 * <p>Response mapping never exposes the owning organization entity or the
 * contacts collection. The client code is never set from a request: it is
 * generated by the service, and the tenant is resolved from the security
 * context.</p>
 */
@Component
public class ClientMapper {

    /**
     * Map an entity into its full response representation.
     *
     * @param client source entity
     * @return response DTO
     */
    public ClientResponse toResponse(Client client) {
        return ClientResponse.builder()
                .id(client.getId())
                .clientCode(client.getClientCode())
                .companyName(client.getCompanyName())
                .legalName(client.getLegalName())
                .email(client.getEmail())
                .phone(client.getPhone())
                .website(client.getWebsite())
                .industry(client.getIndustry())
                .companySize(client.getCompanySize())
                .country(client.getCountry())
                .state(client.getState())
                .city(client.getCity())
                .address(client.getAddress())
                .postalCode(client.getPostalCode())
                .timezone(client.getTimezone())
                .description(client.getDescription())
                .notes(client.getNotes())
                .isActive(client.isActive())
                .createdOn(client.getCreatedOn())
                .updatedOn(client.getUpdatedOn())
                .build();
    }

    /**
     * Map an entity into its lightweight summary representation.
     *
     * @param client source entity
     * @return summary DTO
     */
    public ClientSummaryResponse toSummaryResponse(Client client) {
        return ClientSummaryResponse.builder()
                .id(client.getId())
                .clientCode(client.getClientCode())
                .companyName(client.getCompanyName())
                .industry(client.getIndustry())
                .isActive(client.isActive())
                .build();
    }

    /**
     * Build a transient entity from a creation request. Only business profile
     * fields are mapped; the client code and the organization are set by the
     * service.
     *
     * @param request creation payload
     * @return transient entity
     */
    public Client toEntity(CreateClientRequest request) {
        Client client = new Client();
        applyProfileFields(client, request.getCompanyName(), request.getLegalName(), request.getEmail(),
                request.getPhone(), request.getWebsite(), request.getIndustry(), request.getCompanySize(),
                request.getCountry(), request.getState(), request.getCity(), request.getAddress(),
                request.getPostalCode(), request.getTimezone(), request.getDescription(), request.getNotes());
        return client;
    }

    /**
     * Apply updatable profile fields from an update request onto an existing
     * entity. Immutable fields (id, client code, tenant, timestamps, active,
     * deleted) are never touched.
     *
     * @param client  target entity
     * @param request update payload
     */
    public void updateEntity(Client client, UpdateClientRequest request) {
        applyProfileFields(client, request.getCompanyName(), request.getLegalName(), request.getEmail(),
                request.getPhone(), request.getWebsite(), request.getIndustry(), request.getCompanySize(),
                request.getCountry(), request.getState(), request.getCity(), request.getAddress(),
                request.getPostalCode(), request.getTimezone(), request.getDescription(), request.getNotes());
    }

    /**
     * Copy the shared profile fields onto an entity.
     */
    private void applyProfileFields(Client client, String companyName, String legalName, String email,
                                    String phone, String website, String industry, CompanySize companySize,
                                    String country, String state, String city, String address,
                                    String postalCode, String timezone, String description, String notes) {
        client.setCompanyName(companyName);
        client.setLegalName(legalName);
        client.setEmail(email);
        client.setPhone(phone);
        client.setWebsite(website);
        client.setIndustry(industry);
        client.setCompanySize(companySize);
        client.setCountry(country);
        client.setState(state);
        client.setCity(city);
        client.setAddress(address);
        client.setPostalCode(postalCode);
        client.setTimezone(timezone);
        client.setDescription(description);
        client.setNotes(notes);
    }
}