package com.ayshriv.recruitment.job.entity;

import com.ayshriv.recruitment.client.entity.Client;
import com.ayshriv.recruitment.common.entity.BaseEntity;
import com.ayshriv.recruitment.organization.entity.Organization;
import com.ayshriv.recruitment.user.entity.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a job / opening that a recruitment agency manages on behalf of a
 * client company.
 *
 * <p>A job always belongs to exactly one {@link Organization} (the recruitment
 * agency) and one {@link Client}, and can never be moved to another tenant;
 * the tenant is the hard isolation boundary. Even though the owning client
 * already carries the organization, the job also keeps a direct organization
 * reference so that every tenant filter is explicit and efficient.</p>
 *
 * <p>The recruitment hierarchy is {@code Organization → Client → Job →
 * Application → Candidate}. Job codes such as {@code JOB-000001} are generated
 * by the backend and unique within the owning organization.</p>
 *
 * <p>The common persistence fields are inherited from {@link BaseEntity}.</p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "JOBS",
        uniqueConstraints = @UniqueConstraint(
                name = "UK_JOBS_ORGANIZATION_JOB_CODE",
                columnNames = {"ORGANIZATION_ID", "JOB_CODE"}))
public class Job extends BaseEntity {

    /**
     * Human readable job code generated by the backend, for example
     * {@code JOB-000001}. Never accepted from a client request and never
     * reused after a soft delete.
     */
    @Basic(optional = false)
    @Column(name = "JOB_CODE", nullable = false, length = 20)
    private String jobCode;

    /**
     * Display title of the job, for example {@code Senior Java Backend Developer}.
     */
    @Basic(optional = false)
    @Column(name = "TITLE", nullable = false, length = 200)
    private String title;

    /**
     * Long description of the job.
     */
    @Column(name = "DESCRIPTION", length = 4000)
    private String description;

    /**
     * Required skills and qualifications.
     */
    @Column(name = "REQUIREMENTS", length = 4000)
    private String requirements;

    /**
     * Day to day responsibilities.
     */
    @Column(name = "RESPONSIBILITIES", length = 4000)
    private String responsibilities;

    /**
     * Free form work location label, for example {@code Bangalore}.
     */
    @Column(name = "LOCATION", length = 200)
    private String location;

    /**
     * Country where the work is based.
     */
    @Column(name = "COUNTRY", length = 100)
    private String country;

    /**
     * State / province where the work is based.
     */
    @Column(name = "STATE", length = 100)
    private String state;

    /**
     * City where the work is based.
     */
    @Column(name = "CITY", length = 100)
    private String city;

    /**
     * Whether the role can be performed remotely.
     */
    @Basic(optional = false)
    @Column(name = "IS_REMOTE", nullable = false)
    private boolean remote;

    /**
     * Contract arrangement, stored as its string value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "EMPLOYMENT_TYPE", length = 30)
    private EmploymentType employmentType;

    /**
     * Seniority band, stored as its string value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "EXPERIENCE_LEVEL", length = 20)
    private ExperienceLevel experienceLevel;

    /**
     * Minimum years of experience required.
     */
    @Column(name = "MIN_EXPERIENCE")
    private Integer minExperience;

    /**
     * Maximum years of experience required.
     */
    @Column(name = "MAX_EXPERIENCE")
    private Integer maxExperience;

    /**
     * Minimum offered annual salary.
     */
    @Column(name = "SALARY_MIN", precision = 15, scale = 2)
    private BigDecimal salaryMin;

    /**
     * Maximum offered annual salary.
     */
    @Column(name = "SALARY_MAX", precision = 15, scale = 2)
    private BigDecimal salaryMax;

    /**
     * ISO 4217 currency code of the salary, for example {@code INR}.
     */
    @Column(name = "CURRENCY", length = 10)
    private String currency;

    /**
     * Department within the client company, for example {@code Engineering}.
     */
    @Column(name = "DEPARTMENT", length = 100)
    private String department;

    /**
     * Number of open positions covered by this job.
     */
    @Basic(optional = false)
    @Column(name = "NUMBER_OF_OPENINGS", nullable = false)
    private Integer numberOfOpenings;

    /**
     * Lifecycle state, stored as its string value. New jobs always start as
     * {@code DRAFT}; transitions are enforced by the status transition service.
     */
    @Enumerated(EnumType.STRING)
    @Basic(optional = false)
    @Column(name = "STATUS", nullable = false, length = 20)
    private JobStatus status;

    /**
     * Urgency band, stored as its string value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "PRIORITY", length = 20)
    private JobPriority priority;

    /**
     * Timestamp when the job was published, set by the publish action.
     */
    @Column(name = "PUBLISHED_ON")
    private LocalDateTime publishedOn;

    /**
     * Last date applications are accepted.
     */
    @Column(name = "CLOSING_DATE")
    private LocalDate closingDate;

    /**
     * Owning tenant (the recruitment agency). Never changed after creation.
     */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "ORGANIZATION_ID", nullable = false)
    private Organization organization;

    /**
     * Owning client company.
     *
     * <p>Lazy loaded and never serialized; only the summary fields are exposed
     * through response DTOs.</p>
     */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "CLIENT_ID", nullable = false)
    private Client client;

    /**
     * User who created the job.
     *
     * <p>Resolved from the authenticated user when user authentication is
     * active. Today API key authentication only carries the organization, so
     * this reference may be {@code null} for jobs created through API keys;
     * the mapping is intentionally nullable and extensible.</p>
     */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY")
    private User createdBy;

    /**
     * Owning tenant identifier, safe to access without initializing the lazy
     * relationship target.
     *
     * @return organization id or {@code null} when not set
     */
    public Long getOrganizationId() {
        return organization != null ? organization.getId() : null;
    }

    /**
     * Owning client identifier, safe to access without initializing the lazy
     * relationship target.
     *
     * @return client id or {@code null} when not set
     */
    public Long getClientId() {
        return client != null ? client.getId() : null;
    }

    /**
     * Reference-only constructor used when setting associations by id.
     *
     * @param id job primary key
     */
    public Job(Long id) {
        super(id);
    }
}
