-- Module 05: Job Management.
--
-- Creates the JOBS table. A job belongs to exactly one organization (the
-- recruitment agency) and exactly one client company. Even though the client
-- already belongs to an organization, the job keeps a direct ORGANIZATION_ID
-- foreign key so tenant filtering is explicit and efficient; together with
-- CLIENT_ID it makes cross-tenant relationships impossible at the database
-- level.
--
-- Job codes (JOB-000001, JOB-000002, ...) are generated by the backend and
-- are unique within an organization. The composite unique constraint below is
-- the database safety net that makes concurrent allocation race-free: the
-- service serializes allocation per tenant with a pessimistic lock on the
-- organization row (see JobService / OrganizationRepository) and this
-- constraint guarantees uniqueness even if allocation ever raced.
--
-- CREATED_BY tracks the user who created the job. Today API key
-- authentication only carries the organization (no acting user), so the
-- column is intentionally nullable and is set whenever user authentication is
-- available; the resolution mechanism is designed to be extensible.
--
-- One CREATE INDEX per lookup strategy used by the HQL / JPQL queries.

CREATE TABLE JOBS (
    ID                  BIGSERIAL     PRIMARY KEY,
    CREATED_ON          TIMESTAMP(6)  NOT NULL,
    UPDATED_ON          TIMESTAMP(6)  NOT NULL,
    IS_ACTIVE           BOOLEAN       NOT NULL,
    IS_DELETED          BOOLEAN       NOT NULL,
    JOB_CODE            VARCHAR(20)   NOT NULL,
    TITLE               VARCHAR(200)  NOT NULL,
    DESCRIPTION         VARCHAR(4000),
    REQUIREMENTS        VARCHAR(4000),
    RESPONSIBILITIES    VARCHAR(4000),
    LOCATION            VARCHAR(200),
    COUNTRY             VARCHAR(100),
    STATE               VARCHAR(100),
    CITY                VARCHAR(100),
    IS_REMOTE           BOOLEAN       NOT NULL,
    EMPLOYMENT_TYPE     VARCHAR(30),
    EXPERIENCE_LEVEL    VARCHAR(20),
    MIN_EXPERIENCE      INTEGER,
    MAX_EXPERIENCE      INTEGER,
    SALARY_MIN          NUMERIC(15, 2),
    SALARY_MAX          NUMERIC(15, 2),
    CURRENCY            VARCHAR(10),
    DEPARTMENT          VARCHAR(100),
    NUMBER_OF_OPENINGS  INTEGER       NOT NULL,
    STATUS              VARCHAR(20)   NOT NULL,
    PRIORITY            VARCHAR(20),
    PUBLISHED_ON        TIMESTAMP(6),
    CLOSING_DATE        DATE,
    ORGANIZATION_ID     BIGINT        NOT NULL,
    CLIENT_ID           BIGINT        NOT NULL,
    CREATED_BY          BIGINT,
    CONSTRAINT FK_JOBS_ORGANIZATION
        FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS (ID),
    CONSTRAINT FK_JOBS_CLIENT
        FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID),
    CONSTRAINT FK_JOBS_CREATED_BY
        FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
    CONSTRAINT UK_JOBS_ORGANIZATION_JOB_CODE
        UNIQUE (ORGANIZATION_ID, JOB_CODE)
);

CREATE INDEX IDX_JOBS_ORGANIZATION_ID ON JOBS (ORGANIZATION_ID);
CREATE INDEX IDX_JOBS_CLIENT_ID ON JOBS (CLIENT_ID);
CREATE INDEX IDX_JOBS_JOB_CODE ON JOBS (JOB_CODE);
CREATE INDEX IDX_JOBS_STATUS ON JOBS (STATUS);
CREATE INDEX IDX_JOBS_PRIORITY ON JOBS (PRIORITY);
CREATE INDEX IDX_JOBS_EMPLOYMENT_TYPE ON JOBS (EMPLOYMENT_TYPE);
CREATE INDEX IDX_JOBS_EXPERIENCE_LEVEL ON JOBS (EXPERIENCE_LEVEL);
CREATE INDEX IDX_JOBS_CREATED_BY ON JOBS (CREATED_BY);
CREATE INDEX IDX_JOBS_ACTIVE_DELETED ON JOBS (IS_ACTIVE, IS_DELETED);
CREATE INDEX IDX_JOBS_ORGANIZATION_ACTIVE_DELETED ON JOBS (ORGANIZATION_ID, IS_ACTIVE, IS_DELETED);
CREATE INDEX IDX_JOBS_CLIENT_ACTIVE_DELETED ON JOBS (CLIENT_ID, IS_ACTIVE, IS_DELETED);
CREATE INDEX IDX_JOBS_ORGANIZATION_CLIENT ON JOBS (ORGANIZATION_ID, CLIENT_ID);
CREATE INDEX IDX_JOBS_ORGANIZATION_STATUS_DELETED ON JOBS (ORGANIZATION_ID, STATUS, IS_DELETED);
