CREATE TABLE ORGANIZATIONS (
    ID          BIGSERIAL   PRIMARY KEY,
    CREATED_ON  TIMESTAMP(6) NOT NULL,
    UPDATED_ON  TIMESTAMP(6) NOT NULL,
    IS_ACTIVE   BOOLEAN     NOT NULL,
    IS_DELETED  BOOLEAN     NOT NULL,
    NAME        VARCHAR(100) NOT NULL
);