-- Module 04: Client / Hiring Company Management.
--
-- Creates the CLIENTS table. Every client belongs to exactly one organization
-- (the recruitment agency) and can never be moved to another one. The
-- ORGANIZATION_ID foreign key makes the owning tenant the hard isolation
-- boundary for the table.
--
-- Client codes (CLI-000001, CLI-000002, ...) are generated by the backend and
-- are unique within an organization. The composite unique constraint below is
-- the database safety net that makes concurrent allocation race-free: the
-- service serializes allocation per tenant with a pessimistic lock on the
-- organization row (see ClientService / OrganizationRepository) and this
-- constraint guarantees uniqueness even if allocation ever raced.
--
-- Email uniqueness is deliberately enforced at the application layer (see
-- ClientService) with an ORGANIZATION_ID + EMAIL scoped lookup instead of a
-- database UNIQUE constraint so that:
--   1. Two different organizations may register the same email.
--   2. A soft-deleted client does not block reuse of their email address.
--
-- One CREATE INDEX per lookup strategy used by the HQL / JPQL queries.

CREATE TABLE CLIENTS (
    ID              BIGSERIAL     PRIMARY KEY,
    CREATED_ON      TIMESTAMP(6)  NOT NULL,
    UPDATED_ON      TIMESTAMP(6)  NOT NULL,
    IS_ACTIVE       BOOLEAN       NOT NULL,
    IS_DELETED      BOOLEAN       NOT NULL,
    CLIENT_CODE     VARCHAR(20)   NOT NULL,
    COMPANY_NAME    VARCHAR(200)  NOT NULL,
    LEGAL_NAME      VARCHAR(255),
    EMAIL           VARCHAR(255)  NOT NULL,
    PHONE           VARCHAR(30),
    WEBSITE         VARCHAR(255),
    INDUSTRY        VARCHAR(100),
    COMPANY_SIZE    VARCHAR(20),
    COUNTRY         VARCHAR(100),
    STATE           VARCHAR(100),
    CITY            VARCHAR(100),
    ADDRESS         VARCHAR(500),
    POSTAL_CODE     VARCHAR(20),
    TIMEZONE        VARCHAR(50),
    DESCRIPTION     VARCHAR(2000),
    NOTES           VARCHAR(2000),
    ORGANIZATION_ID BIGINT        NOT NULL,
    CONSTRAINT FK_CLIENTS_ORGANIZATION
        FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS (ID),
    CONSTRAINT UK_CLIENTS_ORGANIZATION_CLIENT_CODE
        UNIQUE (ORGANIZATION_ID, CLIENT_CODE)
);

CREATE INDEX IDX_CLIENTS_ORGANIZATION_ID ON CLIENTS (ORGANIZATION_ID);
CREATE INDEX IDX_CLIENTS_CLIENT_CODE ON CLIENTS (CLIENT_CODE);
CREATE INDEX IDX_CLIENTS_EMAIL ON CLIENTS (EMAIL);
CREATE INDEX IDX_CLIENTS_ORGANIZATION_EMAIL ON CLIENTS (ORGANIZATION_ID, EMAIL);
CREATE INDEX IDX_CLIENTS_ACTIVE_DELETED ON CLIENTS (IS_ACTIVE, IS_DELETED);
CREATE INDEX IDX_CLIENTS_ORGANIZATION_ACTIVE_DELETED ON CLIENTS (ORGANIZATION_ID, IS_ACTIVE, IS_DELETED);