CREATE TABLE API_KEYS (
    ID              BIGSERIAL   PRIMARY KEY,
    CREATED_ON      TIMESTAMP(6) NOT NULL,
    UPDATED_ON      TIMESTAMP(6) NOT NULL,
    IS_ACTIVE       BOOLEAN     NOT NULL,
    IS_DELETED      BOOLEAN     NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    KEY_PREFIX      VARCHAR(12) NOT NULL,
    KEY_HASH        VARCHAR(64) NOT NULL,
    EXPIRES_AT      TIMESTAMP(6),
    LAST_USED_AT    TIMESTAMP(6),
    DESCRIPTION     VARCHAR(500),
    ORGANIZATION_ID BIGINT      NOT NULL,
    CONSTRAINT FK_API_KEYS_ORGANIZATION
        FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS (ID)
);

CREATE INDEX IDX_API_KEYS_KEY_PREFIX ON API_KEYS (KEY_PREFIX);
CREATE INDEX IDX_API_KEYS_KEY_HASH ON API_KEYS (KEY_HASH);
CREATE INDEX IDX_API_KEYS_ORGANIZATION_ID ON API_KEYS (ORGANIZATION_ID);
CREATE INDEX IDX_API_KEYS_ACTIVE_DELETED ON API_KEYS (IS_ACTIVE, IS_DELETED);